// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: emailtemplate.sql

package sqlc

import (
	"context"
)

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT id, template_name, subject, body FROM notification_template WHERE template_name = $1
`

type GetTemplateByNameRow struct {
	ID           int32
	TemplateName string
	Subject      string
	Body         string
}

func (q *Queries) GetTemplateByName(ctx context.Context, templateName string) (GetTemplateByNameRow, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, templateName)
	var i GetTemplateByNameRow
	err := row.Scan(
		&i.ID,
		&i.TemplateName,
		&i.Subject,
		&i.Body,
	)
	return i, err
}
