// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationHistory struct {
	ID           int32
	Recipient    string
	TemplateID   int32
	Status       string
	ErrorMessage pgtype.Text
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type NotificationTemplate struct {
	ID           int32
	TemplateName string
	Subject      string
	Body         string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
